import { NextRequest } from "next/server";

/**
 * Validate API Key for protected routes (cron jobs, admin actions)
 * 
 * Security:
 * - CRON_SECRET is required in production
 * - In development, allows bypass if CRON_SECRET is not set (with warning)
 * - Supports Vercel Cron header, Bearer token, and query parameter authentication
 */
export function validateApiKey(request: NextRequest): boolean {
    const cronSecret = process.env.CRON_SECRET;
    const isDevelopment = process.env.NODE_ENV === "development";

    // Check Vercel Cron header first (auto-generated by Vercel for cron jobs)
    const vercelCron = request.headers.get("x-vercel-cron");
    if (vercelCron === "1") return true;

    // Security: CRON_SECRET is REQUIRED in production
    if (!cronSecret) {
        if (isDevelopment) {
            console.warn("[Auth] CRON_SECRET not set in development mode, allowing unauthenticated access");
            return true;
        }
        // In production, always require CRON_SECRET to be set
        console.error("[Auth] CRON_SECRET not set in production! Denying access.");
        return false;
    }

    // Check Authorization header (Bearer token)
    const authHeader = request.headers.get("authorization");
    if (authHeader?.startsWith("Bearer ")) {
        const token = authHeader.substring(7);
        if (token === cronSecret) return true;
    }

    // Check query parameter (for cron-job.org compatibility)
    const keyParam = request.nextUrl.searchParams.get("key");
    if (keyParam === cronSecret) return true;

    return false;
}

/**
 * Helper to return standardized auth error response
 */
export function authErrorResponse() {
    return {
        error: "Unauthorized",
        message: "Valid API key required. Pass via ?key= or Authorization: Bearer header."
    };
}
